#!/bin/bash

ip=`echo $SSH_CONNECTION | cut -d " " -f 1`

COMMAND=`ps | head -n 2 | tail -n 1`
COMMAND=${COMMAND##*( )} #TRIM

pid=`echo $COMMAND | cut -d " " -f 1`
tty=`echo $COMMAND | cut -d " " -f 2`

JSON_FORMAT_STRING='{ip: $ip, user: $user, pid: $pid, tty: $tty}'
JSON_PAYLOAD=$(jq -n --compact-output \
                --arg ip "$ip" \
                --arg user "$USER" \
                --arg pid "$pid" \
                --arg tty "$tty" \
                "$JSON_FORMAT_STRING")

echo "/login $JSON_PAYLOAD" | nc localhost 8080 > /dev/null
